// Parsed schedule data from schedule.csv
const scheduleData = [
  { startTime: "11:00 AM", endTime: "6:00 PM", activity: "ECP Guest Services Desk Open", location: "Deck 5, Aft", day: "Friday February 20 2026" },
  { startTime: "Noon", endTime: "3:00 PM", activity: "Live Music", location: "Scotty's Taproom, 5 (Duck and Dog Pub)", day: "Friday February 20 2026" },
  { startTime: "Noon", endTime: "10:15 PM", activity: "Leap Event Tech Photo/Auto Sales Office Open", location: "Studio B Lobby, 3 Aft", day: "Friday February 20 2026" },
  { startTime: "12:30 PM", endTime: "12:50 PM", activity: "Star Trek: The Cruise Orientation with Cruise Director JT", location: "Imperial Lounge, 5", day: "Friday February 20 2026" },
  { startTime: "1:40 PM", endTime: "2:00 PM", activity: "Star Trek: The Cruise Orientation with Cruise Director JT", location: "Imperial Lounge, 5", day: "Friday February 20 2026" },
  { startTime: "2:30 PM", endTime: "3:30 PM", activity: "Cruise Collective Alumni Mixer", location: "Sapphire Dining Room, 3", day: "Friday February 20 2026" },
  { startTime: "2:30 PM", endTime: "4:00 PM", activity: "Live Music", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Friday February 20 2026" },
  { startTime: "3:00 PM", endTime: "3:30 PM", activity: "Friends of Bill W.", location: "Prime Directive Grille, 4 (Chops)", day: "Friday February 20 2026" },
  { startTime: "3:30 PM", endTime: "4:00 PM", activity: "Countdown to Launch with DJ Miss Ninja", location: "Pool Stage, 11", day: "Friday February 20 2026" },
  { startTime: "4:00 PM", endTime: "", activity: "Star Trek: The Cruise IX Departs Port Canaveral", location: "", day: "Friday February 20 2026" },
  { startTime: "4:00 PM", endTime: "5:00 PM", activity: "Launch Party and Introduction of the Cast of Star Trek: The Cruise IX", location: "Pool Stage, 11", day: "Friday February 20 2026" },
  { startTime: "4:30 PM", endTime: "", activity: "Star Trek: The Cruise Group Community Room Signups Begin", location: "The Observation Lounge, 14 (Blue Moon)", day: "Friday February 20 2026" },
  { startTime: "5:00 PM", endTime: "5:30 PM", activity: "Icebreaker Meetup hosted by The Morale Officers", location: "Scotty's Taproom, 5 (Duck and Dog Pub)", day: "Friday February 20 2026" },
  { startTime: "5:00 PM", endTime: "6:00 PM", activity: "Photo Session: Max Grodénchik", location: "Imperial Lounge, 5", day: "Friday February 20 2026" },
  { startTime: "5:00 PM", endTime: "9:00 PM", activity: "Fan Makeup with Thomas Surprenant (fee applies)", location: "Quark's Bar, 4 (Boleros)", day: "Friday February 20 2026" },
  { startTime: "5:30 PM", endTime: "6:00 PM", activity: "Sing-a-long with Captain Brian Wilk", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Friday February 20 2026" },
  { startTime: "5:30 PM", endTime: "6:30 PM", activity: "Meet the Federation Advisors and Science Squad featuring Michael & Denise Okuda, Michael Westmore, Lolita Fatjo, Dr. Erin Macdonald, Dr. Mohamed Noor, Dr. Trek Larry Nemecek, and Filmmaker David Zappone hosted by Robb Pearlman", location: "Studio B, 3", day: "Friday February 20 2026" },
  { startTime: "5:30 PM", endTime: "6:30 PM", activity: "LGBTQIA Meetup hosted by The Morale Officers", location: "The Observation Lounge, 14 (Blue Moon)", day: "Friday February 20 2026" },
  { startTime: "7:00 PM", endTime: "8:15 PM", activity: "Star Trek: The Cruise IX Welcome Show featuring Star Trek Game Night! (Guests with Blue SeaPass Cards)", location: "The Lyric Theatre, 3 & 4", day: "Friday February 20 2026" },
  { startTime: "7:00 PM", endTime: "8:15 PM", activity: "Photo Session: William Shatner, Armin Shimerman, John Billingsley (Guests with Red SeaPass Cards)", location: "Sapphire Dining Room, 5", day: "Friday February 20 2026" },
  { startTime: "7:00 PM", endTime: "9:00 PM", activity: "Beta Shift Karaoke Lounge", location: "The Observation Lounge, 14 (Blue Moon)", day: "Friday February 20 2026" },
  { startTime: "7:30 PM", endTime: "8:15 PM", activity: "Star Trek Trivia: Let's Latinum - Strip Stumpers with Special Guest Chase Masterson", location: "Imperial Lounge, 5", day: "Friday February 20 2026" },
  { startTime: "8:00 PM", endTime: "8:30 PM", activity: "Sing-a-long with Captain Brian Wilk", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Friday February 20 2026" },
  { startTime: "9:00 PM", endTime: "9:45 PM", activity: "Star Trek Trivia: Tendi's Trippy Trivia Twenty with Special Guest Noël Wells", location: "Imperial Lounge, 5", day: "Friday February 20 2026" },
  { startTime: "9:00 PM", endTime: "10:15 PM", activity: "Star Trek: The Cruise IX Welcome Show featuring Star Trek Game Night! (Guests with Red SeaPass Cards)", location: "The Lyric Theatre, 3 & 4", day: "Friday February 20 2026" },
  { startTime: "9:00 PM", endTime: "10:15 PM", activity: "Photo Session: William Shatner, Armin Shimerman, John Billingsley (Guests with Blue SeaPass Cards)", location: "Sapphire Dining Room, 5", day: "Friday February 20 2026" },
  { startTime: "10:00 PM", endTime: "11:30 PM", activity: "Chase Masterson's Karaoke Party", location: "Imperial Lounge, 5", day: "Friday February 20 2026" },
  { startTime: "10:30 PM", endTime: "10:45 PM", activity: "Star Trek: The Cruise X 2027 Briefing and Mission Orders", location: "Star Trek: The Cruise Promenade, 5 / Studio B, 3 / Imperial Lounge, 5", day: "Friday February 20 2026" },
  { startTime: "10:30 PM", endTime: "12:30 AM", activity: "Rep Your Star Trek Party featuring DJ Miss Ninja", location: "Star Trek: The Cruise Promenade, 5", day: "Friday February 20 2026" },
  { startTime: "10:30 PM", endTime: "Midnight", activity: "Rep Your Star Trek Party featuring Band 47", location: "Studio B, 3", day: "Friday February 20 2026" },
  { startTime: "11:00 PM", endTime: "1:15 AM", activity: "Star Trek Movie Under The Stars: Star Trek: The Motion Picture", location: "Pool Deck, 11", day: "Friday February 20 2026" },
  { startTime: "11:30 PM", endTime: "2:00 AM", activity: "Rep Your Star Trek After Party with (TBD Ship DJ Name)", location: "The Observation Lounge, 14 (Blue Moon)", day: "Friday February 20 2026" },
  { startTime: "8:00 AM", endTime: "10:15 PM", activity: "Leap Event Tech Photo/Auto Sales Office Open", location: "Studio B Lobby, 3 Aft", day: "Saturday February 21 2026" },
  { startTime: "8:30 AM", endTime: "9:30 AM", activity: "Office Hours Breakfast with Dr. Mohamed Noor", location: "Windjammer Buffet, 11", day: "Saturday February 21 2026" },
  { startTime: "9:00 AM", endTime: "9:45 AM", activity: "Star Trek: Deep Space Nine Episode on the Promenade Screen: In the Pale Moonlight", location: "Star Trek: The Cruise Promenade, 5", day: "Saturday February 21 2026" },
  { startTime: "9:00 AM", endTime: "10:00 AM", activity: "Photo Session: Avaah Blackwell, Raven Dauda, David Benjamin Tomlinson", location: "Imperial Lounge, 5", day: "Saturday February 21 2026" },
  { startTime: "9:00 AM", endTime: "10:00 AM", activity: "Book Club with Robb Pearlman: Star Trek: The Original Series: Lost to Eternity by Greg Cox", location: "The Observation Lounge, 14 (Blue Moon)", day: "Saturday February 21 2026" },
  { startTime: "9:00 AM", endTime: "10:15 AM", activity: "Chase Masterson and Friends Be Kind Charity Breakfast (Ticket required. Sold out)", location: "Sapphire Dining Room, 3", day: "Saturday February 21 2026" },
  { startTime: "9:00 AM", endTime: "6:00 PM", activity: "ECP Next Cruise Lounge Open", location: "ECP Next Cruise Lounge, 6", day: "Saturday February 21 2026" },
  { startTime: "9:00 AM", endTime: "6:00 PM", activity: "ECP Guest Services Desk Open", location: "Deck 5, Aft", day: "Saturday February 21 2026" },
  { startTime: "9:30 AM", endTime: "10:30 AM", activity: "Photo Session: Connor Trinneer, Anthony Montgomery, Dominic Keating", location: "Sapphire Dining Room, 5", day: "Saturday February 21 2026" },
  { startTime: "9:30 AM", endTime: "11:00 AM", activity: "Photo Session: Walter Koenig", location: "Sapphire Dining Room, 5", day: "Saturday February 21 2026" },
  { startTime: "9:30 AM", endTime: "8:30 PM", activity: "Lightspeed Fine Art Gallery Grand Opening", location: "Aquanauts, 12 Aft (Adventure Ocean-Port Side)", day: "Saturday February 21 2026" },
  { startTime: "10:00 AM", endTime: "11:00 AM", activity: "Potpourri with William Shatner (Open Seating)", location: "The Lyric Theatre, 3 & 4", day: "Saturday February 21 2026" },
  { startTime: "10:00 AM", endTime: "11:00 AM", activity: "Mastering Shakespeare with Armin Shimerman", location: "Studio B, 3", day: "Saturday February 21 2026" },
  { startTime: "10:00 AM", endTime: "2:00 PM", activity: "Fan Makeup with Thomas Surprenant (fee applies)", location: "Quark's Bar, 4 (Boleros)", day: "Saturday February 21 2026" },
  { startTime: "10:15 AM", endTime: "1:00 PM", activity: "Star Trek: The Cruise Group Community Room Open", location: "The Observation Lounge, 14 (Blue Moon)", day: "Saturday February 21 2026" },
  { startTime: "10:30 AM", endTime: "11:30 AM", activity: "Group Photo Session: Enterprise Trio: Connor Trinneer, Anthony Montgomery, Dominic Keating", location: "Sapphire Dining Room, 5", day: "Saturday February 21 2026" },
  { startTime: "10:30 AM", endTime: "11:30 AM", activity: "Trek, Lose or Draw hosted by Dr. Trek: Larry Nemecek", location: "Imperial Lounge, 5", day: "Saturday February 21 2026" },
  { startTime: "11:30 AM", endTime: "12:30 PM", activity: "Star Trek: Discovery Panel featuring Doug Jones, Anthony Rapp, Avaah Blackwell, Raven Dauda, and David Benjamin Tomlinson hosted by Dr. Erin Macdonald (Open Seating)", location: "The Lyric Theatre, 3 & 4", day: "Saturday February 21 2026" },
  { startTime: "11:30 AM", endTime: "12:30 PM", activity: "Star Trek: Discovery Panel Simulcast", location: "Star Trek: The Cruise Promenade, 5", day: "Saturday February 21 2026" },
  { startTime: "11:30 AM", endTime: "12:30 PM", activity: "Science Seminar: Current and Practical Research in Evolutionary Biology presented by Dr. Mohamed Noor", location: "Studio B, 3", day: "Saturday February 21 2026" },
  { startTime: "11:30 AM", endTime: "12:30 PM", activity: "Photo Session: Tawny Newsome, Eugene Cordero, Noël Wells", location: "Sapphire Dining Room, 5", day: "Saturday February 21 2026" },
  { startTime: "11:30 AM", endTime: "12:45 PM", activity: "Taste of Royal with Michael and Denise Okuda (Ticket required. Sold out)", location: "Giovanni's Table, 11", day: "Saturday February 21 2026" },
  { startTime: "Noon", endTime: "1:00 PM", activity: "Dungeons & Dragons 101 hosted by Todd Stashwick", location: "Imperial Lounge, 5", day: "Saturday February 21 2026" },
  { startTime: "Noon", endTime: "10:00 PM", activity: "Federation Trading Post Merch Store Grand Opening", location: "Federation Trading Post, 12 (Optix Teen Club)", day: "Saturday February 21 2026" },
  { startTime: "12:30 PM", endTime: "1:30 PM", activity: "Photo Session: Lower Decks Trio: Tawny Newsome, Eugene Cordero, Noël Wells", location: "Sapphire Dining Room, 5", day: "Saturday February 21 2026" },
  { startTime: "1:00 PM", endTime: "1:45 PM", activity: "Michael Westmore Documentary Preview and Panel featuring Michael Westmore, Lolita Fatjo, and David Zappone of 455 Films (Open Seating)", location: "The Lyric Theatre, 3 & 4", day: "Saturday February 21 2026" },
  { startTime: "1:00 PM", endTime: "2:00 PM", activity: "Science Seminar: This Year In Space Science presented Dr. Erin Macdonald", location: "Studio B, 3", day: "Saturday February 21 2026" },
  { startTime: "2:00 PM", endTime: "2:30 PM", activity: "Chase Masterson's Alien Water Wars: The Final Splash!", location: "Pool Deck, 11", day: "Saturday February 21 2026" },
  { startTime: "2:00 PM", endTime: "2:45 PM", activity: "Talking Trek: The Official Star Trek Fleet Command Podcast with UltimatDJz and Griffin", location: "The Observation Lounge, 14 (Blue Moon)", day: "Saturday February 21 2026" },
  { startTime: "2:00 PM", endTime: "4:00 PM", activity: "Dungeons & Dragons hosted by Todd Stashwick & Friends", location: "Imperial Lounge, 5", day: "Saturday February 21 2026" },
  { startTime: "2:15 PM", endTime: "3:15 PM", activity: "Mime over Matter featuring Doug Jones", location: "Studio B, 3", day: "Saturday February 21 2026" },
  { startTime: "2:30 PM", endTime: "3:30 PM", activity: "Sushi and Sake Pairing with Anthony Montgomery (Ticket required. Sold out)", location: "Replicator Sushi, 5 (Izumi)", day: "Saturday February 21 2026" },
  { startTime: "3:00 PM", endTime: "3:30 PM", activity: "Friends of Bill W.", location: "Prime Directive Grille, 4 (Chops)", day: "Saturday February 21 2026" },
  { startTime: "3:00 PM", endTime: "4:00 PM", activity: "Star Trek: The Original Series 60th Anniversary Panel featuring Walter Koenig, Tanya Lemani, Sean Kenney, and Sandra Gimpel hosted by Jonathan Frakes and Daren Dochterman", location: "The Lyric Theatre, 3 & 4", day: "Saturday February 21 2026" },
  { startTime: "3:00 PM", endTime: "4:00 PM", activity: "Star Trek: The Original Series 60th Anniversary Panel Simulcast", location: "Star Trek: The Cruise Promenade, 5", day: "Saturday February 21 2026" },
  { startTime: "3:00 PM", endTime: "4:00 PM", activity: "Tequila Cocktail Tasting with Nana Visitor and Denise Crosby (Ticket required. Sold out)", location: "Sapphire Dining Room, 3", day: "Saturday February 21 2026" },
  { startTime: "3:00 PM", endTime: "4:30 PM", activity: "Star Trek Movie Matinee: Star Trek: Insurrection", location: "Pool Deck, 11", day: "Saturday February 21 2026" },
  { startTime: "3:30 PM", endTime: "5:00 PM", activity: "Live Music", location: "Scotty's Taproom, 5 (Duck and Dog Pub)", day: "Saturday February 21 2026" },
  { startTime: "4:00 PM", endTime: "4:30 PM", activity: "Behind the Bar with Quark featuring bartender Armin Shimerman", location: "Quark's Bar, 4 (Boleros)", day: "Saturday February 21 2026" },
  { startTime: "4:00 PM", endTime: "5:00 PM", activity: "Cocktail Mixology Class with Terry Farrell (Ticket required. Sold out)", location: "The Observation Lounge, 14 (Blue Moon)", day: "Saturday February 21 2026" },
  { startTime: "4:45 PM", endTime: "5:45 PM", activity: "Cruise Collective Alumni Show featuring Robert Picardo & Friends", location: "Studio B, 3", day: "Saturday February 21 2026" },
  { startTime: "4:45 PM", endTime: "5:45 PM", activity: "Crossing Over: Revisiting TOS with Tribble-ations and More presented by Michael and Denise Okuda", location: "Imperial Lounge, 5", day: "Saturday February 21 2026" },
  { startTime: "5:00 PM", endTime: "5:30 PM", activity: "Icebreaker Meetup hosted by The Morale Officers", location: "Scotty's Taproom, 5 (Duck and Dog Pub)", day: "Saturday February 21 2026" },
  { startTime: "5:00 PM", endTime: "5:45 PM", activity: "Star Trek Fleet Command Meetup", location: "Quark's Bar, 4 (Boleros)", day: "Saturday February 21 2026" },
  { startTime: "5:00 PM", endTime: "9:00 PM", activity: "Fan Makeup with Thomas Surprenant (fee applies)", location: "Quark's Bar, 4 (Boleros)", day: "Saturday February 21 2026" },
  { startTime: "5:30 PM", endTime: "6:00 PM", activity: "Bracket Challenge: Captains hosted by Robb Pearlman", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Saturday February 21 2026" },
  { startTime: "5:30 PM", endTime: "6:30 PM", activity: "LGBTQIA Meetup hosted by The Morale Officers", location: "The Observation Lounge, 14 (Blue Moon)", day: "Saturday February 21 2026" },
  { startTime: "6:00 PM", endTime: "6:45 PM", activity: "Photo Session: Jonathan Frakes, Marina Sirtis (Guests with Red SeaPass Cards)", location: "Sapphire Dining Room, 5", day: "Saturday February 21 2026" },
  { startTime: "6:00 PM", endTime: "7:30 PM", activity: "Photo Session: Terry Farrell (Guests with Red SeaPass Cards)", location: "Sapphire Dining Room, 5", day: "Saturday February 21 2026" },
  { startTime: "6:30 PM", endTime: "7:45 PM", activity: "Surprises of a Galactic Kind featuring John de Lancie and Curtis Institute of Music (Guests with Blue SeaPass Cards)", location: "The Lyric Theatre, 3 & 4", day: "Saturday February 21 2026" },
  { startTime: "6:45 PM", endTime: "7:30 PM", activity: "Group Photo Session: TNG Lovebirds: Jonathan Frakes, Marina Sirtis (Guests with Red SeaPass Cards)", location: "Sapphire Dining Room, 5", day: "Saturday February 21 2026" },
  { startTime: "7:15 PM", endTime: "8:15 PM", activity: "The Man Behind the Makeup: Chat with Michael Westmore", location: "Studio B, 3", day: "Saturday February 21 2026" },
  { startTime: "8:00 PM", endTime: "8:30 PM", activity: "Bracket Challenge: Alien Species hosted by Robb Pearlman", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Saturday February 21 2026" },
  { startTime: "8:30 PM", endTime: "9:15 PM", activity: "Photo Session: Jonathan Frakes, Marina Sirtis (Guests with Blue SeaPass Cards)", location: "Sapphire Dining Room, 5", day: "Saturday February 21 2026" },
  { startTime: "8:30 PM", endTime: "10:00 PM", activity: "Photo Session: Terry Farrell (Guests with Blue SeaPass Cards)", location: "Sapphire Dining Room, 5", day: "Saturday February 21 2026" },
  { startTime: "9:00 PM", endTime: "10:15 PM", activity: "Surprises of a Galactic Kind featuring John de Lancie and Curtis Institute of Music (Guests with Red SeaPass Cards)", location: "The Lyric Theatre, 3 & 4", day: "Saturday February 21 2026" },
  { startTime: "9:15 PM", endTime: "10:00 PM", activity: "Group Photo Session: TNG Lovebirds: Jonathan Frakes, Marina Sirtis (Guests with Blue SeaPass Cards)", location: "Sapphire Dining Room, 5", day: "Saturday February 21 2026" },
  { startTime: "9:15 PM", endTime: "10:15 PM", activity: "Chit Chat with Chekov featuring Walter Koenig", location: "Studio B, 3", day: "Saturday February 21 2026" },
  { startTime: "10:30 PM", endTime: "Midnight", activity: "Heroes and Villains Party featuring DJ Miss Ninja", location: "Studio B, 3", day: "Saturday February 21 2026" },
  { startTime: "11:00 PM", endTime: "1:00 AM", activity: "Star Trek Movie Under The Stars: Star Trek (2009)", location: "Pool Deck, 11", day: "Saturday February 21 2026" },
  { startTime: "11:30 PM", endTime: "1:00 AM", activity: "Late Night Movie: Galaxy Quest", location: "Imperial Lounge, 5", day: "Saturday February 21 2026" },
  { startTime: "11:30 PM", endTime: "2:00 AM", activity: "Heroes and Villains After Party with (TBD Ship DJ)", location: "The Observation Lounge, 14 (Blue Moon)", day: "Saturday February 21 2026" },
  { startTime: "9:00 AM", endTime: "9:30 AM", activity: "Yoga for Beginners with Terry Farrell", location: "The Observation Lounge, 14 (Blue Moon)", day: "Sunday February 22 2026" },
  { startTime: "9:00 AM", endTime: "9:45 AM", activity: "Star Trek: The Original Series Episode on the Promenade Screen: The City on the Edge of Forever", location: "Star Trek: The Cruise Promenade, 5", day: "Sunday February 22 2026" },
  { startTime: "9:00 AM", endTime: "1:00 PM", activity: "ECP Next Cruise Lounge Open", location: "ECP Next Cruise Lounge, 6", day: "Sunday February 22 2026" },
  { startTime: "9:00 AM", endTime: "6:00 PM", activity: "ECP Guest Services Desk Open", location: "Deck 5, Aft", day: "Sunday February 22 2026" },
  { startTime: "9:30 AM", endTime: "", activity: "Star Trek: The Cruise Docks In Puerto Plata", location: "", day: "Sunday February 22 2026" },
  { startTime: "10:00 AM", endTime: "Noon", activity: "Open Play Ping Pong", location: "Outdoor Youth Area, 12", day: "Sunday February 22 2026" },
  { startTime: "10:00 AM", endTime: "4:00 PM", activity: "Star Trek: The Cruise Group Community Room Open", location: "The Observation Lounge, 14 (Blue Moon)", day: "Sunday February 22 2026" },
  { startTime: "Noon", endTime: "12:45 PM", activity: "Royal Caribbean presents: Scattergories Challenge", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Sunday February 22 2026" },
  { startTime: "1:00 PM", endTime: "2:45 PM", activity: "Star Trek Movie Matinee: Star Trek Into Darkness", location: "Pool Deck, 11", day: "Sunday February 22 2026" },
  { startTime: "2:00 PM", endTime: "2:45 PM", activity: "Royal Caribbean presents: Name That Tune: Through The Decades", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Sunday February 22 2026" },
  { startTime: "3:00 PM", endTime: "3:30 PM", activity: "Friends of Bill W.", location: "Prime Directive Grille, 4 (Chops)", day: "Sunday February 22 2026" },
  { startTime: "3:30 PM", endTime: "5:00 PM", activity: "Live Music", location: "Scotty's Taproom, 5 (Duck and Dog Pub)", day: "Sunday February 22 2026" },
  { startTime: "4:00 PM", endTime: "5:00 PM", activity: "Potpourri with William Shatner (Open Seating)", location: "The Lyric Theatre, 3 & 4", day: "Sunday February 22 2026" },
  { startTime: "4:00 PM", endTime: "5:00 PM", activity: "Mastering Shakespeare with Armin Shimerman", location: "Studio B, 3", day: "Sunday February 22 2026" },
  { startTime: "4:30 PM", endTime: "", activity: "All Aboard", location: "", day: "Sunday February 22 2026" },
  { startTime: "4:30 PM", endTime: "6:00 PM", activity: "Autograph Session: Tawny Newsome, Eugene Cordero, Noël Wells", location: "Sapphire Dining Room, 5", day: "Sunday February 22 2026" },
  { startTime: "4:30 PM", endTime: "9:00 PM", activity: "Lightspeed Fine Art Gallery Open", location: "Aquanauts, 12 Aft (Adventure Ocean-Port Side)", day: "Sunday February 22 2026" },
  { startTime: "4:30 PM", endTime: "10:00 PM", activity: "Leap Event Tech Photo/Auto Sales Office Open", location: "Studio B Lobby, 3 Aft", day: "Sunday February 22 2026" },
  { startTime: "5:00 PM", endTime: "5:30 PM", activity: "Icebreaker Meetup hosted by The Morale Officers", location: "Scotty's Taproom, 5 (Duck and Dog Pub)", day: "Sunday February 22 2026" },
  { startTime: "5:00 PM", endTime: "5:45 PM", activity: "Trivia with the Science Squad hosted by Dr. Erin Macdonald and Dr. Mohamed Noor", location: "Imperial Lounge, 5", day: "Sunday February 22 2026" },
  { startTime: "5:00 PM", endTime: "6:00 PM", activity: "Special Photo Session: Chase Masterson and Max Grodénchik with the Dabo Wheel", location: "Quark's Bar, 4 (Boleros)", day: "Sunday February 22 2026" },
  { startTime: "5:00 PM", endTime: "9:00 PM", activity: "Fan Makeup with Thomas Surprenant (fee applies)", location: "Quark's Bar, 4 (Boleros)", day: "Sunday February 22 2026" },
  { startTime: "5:30 PM", endTime: "6:00 PM", activity: "Name That Tune: 1960s", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Sunday February 22 2026" },
  { startTime: "5:30 PM", endTime: "6:30 PM", activity: "LGBTQIA Meetup hosted by Robb Pearlman", location: "The Observation Lounge, 14 (Blue Moon)", day: "Sunday February 22 2026" },
  { startTime: "5:30 PM", endTime: "10:00 PM", activity: "Federation Trading Post Merch Store Open", location: "Federation Trading Post, 12 (Optix Teen Club)", day: "Sunday February 22 2026" },
  { startTime: "6:00 PM", endTime: "7:30 PM", activity: "Autograph Session: William Shatner (Guests with Red SeaPass Cards)", location: "Sapphire Dining Room, 5", day: "Sunday February 22 2026" },
  { startTime: "6:30 PM", endTime: "7:45 PM", activity: "Songs I Love to Sing featuring Anthony Rapp (Guests with Blue SeaPass Cards)", location: "The Lyric Theatre, 3 & 4", day: "Sunday February 22 2026" },
  { startTime: "7:00 PM", endTime: "10:00 PM", activity: "Beta Shift Karaoke Lounge", location: "The Observation Lounge, 14 (Blue Moon)", day: "Sunday February 22 2026" },
  { startTime: "7:15 PM", endTime: "8:15 PM", activity: "Chit-Chat with Chekov featuring Walter Koenig", location: "Studio B, 3", day: "Sunday February 22 2026" },
  { startTime: "8:00 PM", endTime: "8:30 PM", activity: "Name That Tune: 1960s", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Sunday February 22 2026" },
  { startTime: "8:30 PM", endTime: "10:00 PM", activity: "Autograph Session: William Shatner (Guests with Blue SeaPass Cards)", location: "Sapphire Dining Room, 5", day: "Sunday February 22 2026" },
  { startTime: "9:00 PM", endTime: "10:15 PM", activity: "Songs I Love to Sing featuring Anthony Rapp (Guests with Red SeaPass Cards)", location: "The Lyric Theatre, 3 & 4", day: "Sunday February 22 2026" },
  { startTime: "9:15 PM", endTime: "10:15 PM", activity: "The Man Behind The Make-Up: Chat with Michael Westmore", location: "Studio B, 3", day: "Sunday February 22 2026" },
  { startTime: "10:30 PM", endTime: "Midnight", activity: "Holodeck '66 Party featuring Band 47", location: "Studio B, 3", day: "Sunday February 22 2026" },
  { startTime: "10:45 PM", endTime: "12:45 AM", activity: "30th Anniversary Showing: Star Trek: First Contact (Open Seating)", location: "The Lyric Theatre, 3 & 4", day: "Sunday February 22 2026" },
  { startTime: "11:00 PM", endTime: "1:00 AM", activity: "Star Trek Movie Under The Stars: Star Trek II: The Wrath of Khan", location: "Pool Deck, 11", day: "Sunday February 22 2026" },
  { startTime: "11:30 PM", endTime: "2:00 AM", activity: "Holodeck After Party with (TBD Ship DJ)", location: "The Observation Lounge, 14 (Blue Moon)", day: "Sunday February 22 2026" },
  { startTime: "9:00 AM", endTime: "9:30 AM", activity: "Body By Starfleet with Robb Pearlman", location: "Pool Stage, 11", day: "Monday February 23 2026" },
  { startTime: "9:00 AM", endTime: "9:45 AM", activity: "Star Trek: The Next Generation Episode on the Promenade Screen: Captain's Holiday", location: "Star Trek: The Cruise Promenade, 5", day: "Monday February 23 2026" },
  { startTime: "9:00 AM", endTime: "1:00 PM", activity: "ECP Next Cruise Lounge Open", location: "ECP Next Cruise Lounge, 6", day: "Monday February 23 2026" },
  { startTime: "9:00 AM", endTime: "6:00 PM", activity: "ECP Guest Services Desk Open", location: "Deck 5, Aft", day: "Monday February 23 2026" },
  { startTime: "9:30 AM", endTime: "", activity: "Star Trek: The Cruise Docks In San Juan", location: "", day: "Monday February 23 2026" },
  { startTime: "10:00 AM", endTime: "Noon", activity: "Open Play Pickleball", location: "Sports Court, 13", day: "Monday February 23 2026" },
  { startTime: "10:00 AM", endTime: "4:00 PM", activity: "Star Trek: The Cruise Group Community Room Open", location: "The Observation Lounge, 14 (Blue Moon)", day: "Monday February 23 2026" },
  { startTime: "Noon", endTime: "12:45 PM", activity: "Royal Caribbean presents: Picture Trivia: World Flags", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Monday February 23 2026" },
  { startTime: "1:00 PM", endTime: "3:00 PM", activity: "Star Trek Movie Matinee: Star Trek VI: The Undiscovered Country", location: "Pool Deck, 11", day: "Monday February 23 2026" },
  { startTime: "2:00 PM", endTime: "2:45 PM", activity: "Royal Caribbean presents: Visual Trivia: Superheroes", location: "Imperial Lounge, 5", day: "Monday February 23 2026" },
  { startTime: "3:00 PM", endTime: "3:30 PM", activity: "Friends of Bill W.", location: "Prime Directive Grille, 4 (Chops)", day: "Monday February 23 2026" },
  { startTime: "3:30 PM", endTime: "5:00 PM", activity: "Live Music", location: "Scotty's Taproom, 5 (Duck and Dog Pub)", day: "Monday February 23 2026" },
  { startTime: "4:30 PM", endTime: "10:00 PM", activity: "Leap Event Tech Photo/Auto Sales Office Open", location: "Studio B Lobby, 3 Aft", day: "Monday February 23 2026" },
  { startTime: "5:00 PM", endTime: "5:30 PM", activity: "Icebreaker Meetup hosted by The Morale Officers", location: "Scotty's Taproom, 5 (Duck and Dog Pub)", day: "Monday February 23 2026" },
  { startTime: "5:00 PM", endTime: "5:45 PM", activity: "Photo Session: Denise Crosby, Nana Visitor", location: "Sapphire Dining Room, 5", day: "Monday February 23 2026" },
  { startTime: "5:00 PM", endTime: "6:00 PM", activity: "The Story of Curtis Through a Personal Lens Presented by John de Lancie, Jonathan Frakes, and the Curtis Institute of Music", location: "Studio B, 3", day: "Monday February 23 2026" },
  { startTime: "5:00 PM", endTime: "6:00 PM", activity: "In the Hot Seat with Connor Trinneer and Special Guest Terry Farrell", location: "Imperial Lounge, 5", day: "Monday February 23 2026" },
  { startTime: "5:00 PM", endTime: "9:00 PM", activity: "Fan Makeup with Thomas Surprenant (fee applies)", location: "Quark's Bar, 4 (Boleros)", day: "Monday February 23 2026" },
  { startTime: "5:30 PM", endTime: "", activity: "All Aboard", location: "", day: "Monday February 23 2026" },
  { startTime: "5:30 PM", endTime: "6:00 PM", activity: "Fun with Kirk and Spock hosted by Robb Pearlman", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Monday February 23 2026" },
  { startTime: "5:30 PM", endTime: "6:30 PM", activity: "LGBTQIA Meetup hosted by Dr. Erin Macdonald", location: "The Observation Lounge, 14 (Blue Moon)", day: "Monday February 23 2026" },
  { startTime: "5:30 PM", endTime: "9:00 PM", activity: "Lightspeed Fine Art Gallery Open", location: "Aquanauts, 12 Aft (Adventure Ocean-Port Side)", day: "Monday February 23 2026" },
  { startTime: "5:45 PM", endTime: "6:30 PM", activity: "Group Photo Session: Tequila Sunrise with Denise Crosby and Nana Visitor", location: "Sapphire Dining Room, 5", day: "Monday February 23 2026" },
  { startTime: "6:00 PM", endTime: "7:30 PM", activity: "Photo Session: Doug Jones, Anthony Rapp, Todd Stashwick (Guests with Red SeaPass Cards)", location: "Sapphire Dining Room, 5", day: "Monday February 23 2026" },
  { startTime: "6:30 PM", endTime: "7:45 PM", activity: "We're in Town for Something Else... Again! - An Improv Show featuring Tawny Newsome and Eugene Cordero (Guests with Blue SeaPass Cards)", location: "The Lyric Theatre, 3 & 4", day: "Monday February 23 2026" },
  { startTime: "7:15 PM", endTime: "8:00 PM", activity: "Star Trek Trivia: Lura's Thok-Provoking Cadet-Master Quiz with Special Guest Gina Yashere", location: "Imperial Lounge, 5", day: "Monday February 23 2026" },
  { startTime: "8:00 PM", endTime: "8:30 PM", activity: "Fun with Kirk and Spock hosted by Robb Pearlman", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Monday February 23 2026" },
  { startTime: "8:00 PM", endTime: "8:45 PM", activity: "The D-Conn Chamber Podcast featuring Connor Trinneer and Dominic Keating and Special Guest Denise Crosby", location: "Studio B, 3", day: "Monday February 23 2026" },
  { startTime: "8:30 PM", endTime: "10:00 PM", activity: "Photo Session: Doug Jones, Anthony Rapp, Todd Stashwick (Guests with Blue SeaPass Cards)", location: "Sapphire Dining Room, 5", day: "Monday February 23 2026" },
  { startTime: "9:00 PM", endTime: "9:45 PM", activity: "Star Trek Trivia: Phlox's Poly-Denobulan Puzzlers with Special Guest John Billingsley", location: "Imperial Lounge, 5", day: "Monday February 23 2026" },
  { startTime: "9:00 PM", endTime: "10:15 PM", activity: "We're in Town for Something Else... Again! - An Improv Show featuring Tawny Newsome and Eugene Cordero (Guests with Red SeaPass Cards)", location: "The Lyric Theatre, 3 & 4", day: "Monday February 23 2026" },
  { startTime: "10:15 PM", endTime: "11:45 PM", activity: "Risa's Festival of the Moon Party featuring Band 47", location: "Pool Stage, 11", day: "Monday February 23 2026" },
  { startTime: "10:45 PM", endTime: "11:30 PM", activity: "This Week In The Night Sky Viewing with Dr. Erin Macdonald", location: "Open Deck, 13 Forward", day: "Monday February 23 2026" },
  { startTime: "11:30 PM", endTime: "2:00 AM", activity: "The Bad Bitch Birthday Bash! Celebrating Tawny Newsome featuring DJ Miss Ninja", location: "Imperial Lounge, 5", day: "Monday February 23 2026" },
  { startTime: "11:45 PM", endTime: "1:45 AM", activity: "Star Trek Movie Under The Stars: Star Trek: Nemesis", location: "Pool Deck, 11", day: "Monday February 23 2026" },
  { startTime: "8:00 AM", endTime: "9:00 PM", activity: "Leap Event Tech Photo/Auto Sales Office Open", location: "Studio B Lobby, 3 Aft", day: "Tuesday February 24 2026" },
  { startTime: "8:30 AM", endTime: "9:30 AM", activity: "Office Hours Breakfast with Dr. Mohamed Noor", location: "Windjammer Buffet, 11", day: "Tuesday February 24 2026" },
  { startTime: "9:00 AM", endTime: "9:45 AM", activity: "Star Trek: Voyager Episode on the Promenade Screen: Counterpoint", location: "Star Trek: The Cruise Promenade, 5", day: "Tuesday February 24 2026" },
  { startTime: "9:00 AM", endTime: "10:00 AM", activity: "Photo Session: Tanya Lemani, Sandra Gimpel, Sean Kenney, and TOS Special Group", location: "Imperial Lounge, 5", day: "Tuesday February 24 2026" },
  { startTime: "9:00 AM", endTime: "10:00 AM", activity: "Book Club with Robb Pearlman: Star Trek: Discovery: Die Standing by John Jackson Miller", location: "The Observation Lounge, 14 (Blue Moon)", day: "Tuesday February 24 2026" },
  { startTime: "9:00 AM", endTime: "10:15 AM", activity: "Pancreatic Cancer Charity Breakfast with Jonathan Frakes, John Billingsley, Armin Shimerman, and Kitty Swink (Ticket required. Sold out)", location: "Giovanni's Table, 11", day: "Tuesday February 24 2026" },
  { startTime: "9:00 AM", endTime: "11:00 AM", activity: "Star Trek: The Cruise T-shirt Size Exchange", location: "Federation Trading Post, 12 (Optix Teen Club)", day: "Tuesday February 24 2026" },
  { startTime: "9:00 AM", endTime: "6:00 PM", activity: "ECP Next Cruise Lounge Open", location: "ECP Next Cruise Lounge, 6", day: "Tuesday February 24 2026" },
  { startTime: "9:00 AM", endTime: "6:00 PM", activity: "ECP Guest Services Desk Open", location: "Deck 5, Aft", day: "Tuesday February 24 2026" },
  { startTime: "9:00 AM", endTime: "9:00 PM", activity: "Federation Trading Post Merch Store Open", location: "Federation Trading Post, 12 (Optix Teen Club)", day: "Tuesday February 24 2026" },
  { startTime: "9:30 AM", endTime: "10:30 AM", activity: "Starfleet Tactical Training: Basic Self Defense with Avaah Blackwell", location: "Studio B, 3", day: "Tuesday February 24 2026" },
  { startTime: "9:30 AM", endTime: "10:30 AM", activity: "Rock Climbing with Anthony Montgomery", location: "Rock Climbing Wall, 13 Aft", day: "Tuesday February 24 2026" },
  { startTime: "9:30 AM", endTime: "11:00 AM", activity: "Photo Session: Gina Yashere, Zoë Steiner", location: "Sapphire Dining Room, 5", day: "Tuesday February 24 2026" },
  { startTime: "9:30 AM", endTime: "11:00 AM", activity: "Autograph Session: Terry Farrell", location: "Sapphire Dining Room, 5", day: "Tuesday February 24 2026" },
  { startTime: "9:30 AM", endTime: "8:30 PM", activity: "Lightspeed Fine Art Gallery Open", location: "Aquanauts, 12 Aft (Adventure Ocean-Port Side)", day: "Tuesday February 24 2026" },
  { startTime: "10:00 AM", endTime: "2:00 PM", activity: "Fan Makeup with Thomas Surprenant (fee applies)", location: "Quark's Bar, 4 (Boleros)", day: "Tuesday February 24 2026" },
  { startTime: "10:15 AM", endTime: "11:15 AM", activity: "Star Trek: The Next Generation Panel featuring Jonathan Frakes, Marina Sirtis, John de Lancie, Denise Crosby hosted by Todd Stashwick (Open Seating)", location: "The Lyric Theatre, 3 & 4", day: "Tuesday February 24 2026" },
  { startTime: "10:15 AM", endTime: "11:15 AM", activity: "Star Trek: The Next Generation Panel Simulcast", location: "Star Trek: The Cruise Promenade, 5", day: "Tuesday February 24 2026" },
  { startTime: "10:30 AM", endTime: "1:15 PM", activity: "Star Trek: The Cruise Group Community Room Open", location: "The Observation Lounge, 14 (Blue Moon)", day: "Tuesday February 24 2026" },
  { startTime: "10:45 AM", endTime: "11:45 AM", activity: "Science Seminar: Temporal Mechanics 101 presented by Dr. Erin Macdonald", location: "Imperial Lounge, 5", day: "Tuesday February 24 2026" },
  { startTime: "11:15 AM", endTime: "12:15 PM", activity: "Origins of the Ferengi featuring Armin Shimerman, Max Grodénchik, and Michael Westmore hosted by Lolita Fatjo", location: "Studio B, 3", day: "Tuesday February 24 2026" },
  { startTime: "Noon", endTime: "1:15 PM", activity: "Star Trek: The Cruise IX T-Shirt Party featuring Sing with Band 47 (Free Drinks!)", location: "Pool Stage, 11", day: "Tuesday February 24 2026" },
  { startTime: "12:15 PM", endTime: "1:45 PM", activity: "Photo Session: John de Lancie, Chase Masterson", location: "Sapphire Dining Room, 5", day: "Tuesday February 24 2026" },
  { startTime: "12:45 PM", endTime: "1:45 PM", activity: "Past Present and Future: 60 Years of Roddenberry Entertainment presented by Rod Roddenberry and Trevor Roth", location: "Studio B, 3", day: "Tuesday February 24 2026" },
  { startTime: "2:00 PM", endTime: "2:45 PM", activity: "Talking Trek: The Official Star Trek Fleet Command Podcast with UltimatDJz and Griffin", location: "The Observation Lounge, 14 (Blue Moon)", day: "Tuesday February 24 2026" },
  { startTime: "2:30 PM", endTime: "3:30 PM", activity: "Science Seminar: Scientific Context of the Original Series presented by Dr. Erin Macdonald and Dr. Mohamed Noor", location: "Studio B, 3", day: "Tuesday February 24 2026" },
  { startTime: "2:30 PM", endTime: "3:30 PM", activity: "Sushi Candy Class with Raven Dauda (Ticket required. Sold out)", location: "Replicator Sushi, 5 (Izumi)", day: "Tuesday February 24 2026" },
  { startTime: "3:00 PM", endTime: "3:30 PM", activity: "Friends of Bill W.", location: "Prime Directive Grille, 4 (Chops)", day: "Tuesday February 24 2026" },
  { startTime: "3:30 PM", endTime: "5:00 PM", activity: "Gorn's Gong Show (Open Seating)", location: "The Lyric Theatre, 3 & 4", day: "Tuesday February 24 2026" },
  { startTime: "3:30 PM", endTime: "5:00 PM", activity: "Gorn's Gong Show Simulcast", location: "Star Trek: The Cruise Promenade, 5", day: "Tuesday February 24 2026" },
  { startTime: "3:30 PM", endTime: "5:00 PM", activity: "Final Table Poker Tournament with Anthony Rapp", location: "Casino Royale, 4", day: "Tuesday February 24 2026" },
  { startTime: "3:30 PM", endTime: "5:00 PM", activity: "Live Music", location: "Scotty's Taproom, 5 (Duck and Dog Pub)", day: "Tuesday February 24 2026" },
  { startTime: "4:00 PM", endTime: "5:00 PM", activity: "Roddenberry Archive Update presented by Michael and Denise Okuda", location: "Imperial Lounge, 5", day: "Tuesday February 24 2026" },
  { startTime: "4:00 PM", endTime: "5:00 PM", activity: "Discussions and Desserts with the Doctors with Dr. Mohamed Noor and John Billingsley (Ticket required. Sold out)", location: "The Observation Lounge, 14 (Blue Moon)", day: "Tuesday February 24 2026" },
  { startTime: "5:00 PM", endTime: "5:30 PM", activity: "Icebreaker Meetup hosted by The Morale Officers", location: "Scotty's Taproom, 5 (Duck and Dog Pub)", day: "Tuesday February 24 2026" },
  { startTime: "5:00 PM", endTime: "6:00 PM", activity: "Be Kind Charity Dabo Tournament hosted by Chase Masterson (Ticket required. Sold out)", location: "Quark's Bar, 4 (Boleros)", day: "Tuesday February 24 2026" },
  { startTime: "5:00 PM", endTime: "9:00 PM", activity: "Fan Makeup with Thomas Surprenant (fee applies)", location: "Quark's Bar, 4 (Boleros)", day: "Tuesday February 24 2026" },
  { startTime: "5:30 PM", endTime: "6:00 PM", activity: "Royal Caribbean presents: Piano Tunes", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Tuesday February 24 2026" },
  { startTime: "5:30 PM", endTime: "6:30 PM", activity: "LGBTQIA Meetup hosted by Robb Pearlman", location: "The Observation Lounge, 14 (Blue Moon)", day: "Tuesday February 24 2026" },
  { startTime: "5:30 PM", endTime: "7:00 PM", activity: "Autograph Session: Armin Shimerman, John Billingsley", location: "Sapphire Dining Room, 5", day: "Tuesday February 24 2026" },
  { startTime: "6:30 PM", endTime: "7:15 PM", activity: "Renewal of Vows with Terry Farrell session #1 (Guests with Red SeaPass Cards)", location: "Imperial Lounge, 5", day: "Tuesday February 24 2026" },
  { startTime: "6:30 PM", endTime: "7:45 PM", activity: "Robert Picardo & Friends Present: Starfleet Academy: Crisis Management Simulations (Guests with Blue SeaPass Cards)", location: "The Lyric Theatre, 3 & 4", day: "Tuesday February 24 2026" },
  { startTime: "7:00 PM", endTime: "10:00 PM", activity: "Beta Shift Karaoke Lounge", location: "The Observation Lounge, 14 (Blue Moon)", day: "Tuesday February 24 2026" },
  { startTime: "7:15 PM", endTime: "8:15 PM", activity: "Scene Study: An Enterprise Table Read Experience hosted by Connor Trinneer", location: "Studio B, 3", day: "Tuesday February 24 2026" },
  { startTime: "8:00 PM", endTime: "8:30 PM", activity: "Royal Caribbean presents: Piano Tunes", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Tuesday February 24 2026" },
  { startTime: "8:30 PM", endTime: "9:15 PM", activity: "Renewal of Vows with Terry Farrell session #2 (Guests with Blue SeaPass Cards)", location: "Imperial Lounge, 5", day: "Tuesday February 24 2026" },
  { startTime: "9:00 PM", endTime: "10:15 PM", activity: "Robert Picardo & Friends Present: Starfleet Academy: Crisis Management Simulations (Guests with Red SeaPass Cards)", location: "The Lyric Theatre, 3 & 4", day: "Tuesday February 24 2026" },
  { startTime: "9:15 PM", endTime: "10:15 PM", activity: "Scene Study: An Enterprise Table Read Experience hosted by Connor Trinneer", location: "Studio B, 3", day: "Tuesday February 24 2026" },
  { startTime: "10:30 PM", endTime: "Midnight", activity: "The Captains Gala featuring Band 47", location: "Sapphire Dining Room, 3", day: "Tuesday February 24 2026" },
  { startTime: "10:45 PM", endTime: "11:45 PM", activity: "Interstellar Improv: An Episodic Overdub Adventure featuring Denise Crosby and Friends", location: "Studio B, 3", day: "Tuesday February 24 2026" },
  { startTime: "11:00 PM", endTime: "1:00 AM", activity: "Star Trek Movie Under The Stars: Star Trek Generations", location: "Pool Deck, 11", day: "Tuesday February 24 2026" },
  { startTime: "Midnight", endTime: "2:00 AM", activity: "Gala After Party: Silent Disco", location: "The Observation Lounge, 14 (Blue Moon)", day: "Tuesday February 24 2026" },
  { startTime: "8:00 AM", endTime: "10:15 PM", activity: "Leap Event Tech Photo/Auto Sales Office Open", location: "Studio B Lobby, 3 Aft", day: "Wednesday February 25 2026" },
  { startTime: "8:30 AM", endTime: "9:30 AM", activity: "Office Hours Breakfast hosted by Dr. Mohamed Noor", location: "Windjammer Buffet, 11", day: "Wednesday February 25 2026" },
  { startTime: "9:00 AM", endTime: "9:30 AM", activity: "A Peek Behind the Curtain (Learn what goes into producing Star Trek: The Cruise)", location: "Imperial Lounge, 5", day: "Wednesday February 25 2026" },
  { startTime: "9:00 AM", endTime: "9:30 AM", activity: "Yoga for Beginners with Terry Farrell", location: "The Observation Lounge, 14 (Blue Moon)", day: "Wednesday February 25 2026" },
  { startTime: "9:00 AM", endTime: "9:45 AM", activity: "Star Trek: The Next Generation Episode on the Promenade Screen: Qpid", location: "Star Trek: The Cruise Promenade, 5", day: "Wednesday February 25 2026" },
  { startTime: "9:00 AM", endTime: "6:00 PM", activity: "ECP Next Cruise Lounge Open", location: "ECP Next Cruise Lounge, 6", day: "Wednesday February 25 2026" },
  { startTime: "9:00 AM", endTime: "6:00 PM", activity: "ECP Guest Services Desk Open", location: "Deck 5, Aft", day: "Wednesday February 25 2026" },
  { startTime: "9:00 AM", endTime: "9:00 PM", activity: "Federation Trading Post Merch Store Open", location: "Federation Trading Post, 12 (Optix Teen Club)", day: "Wednesday February 25 2026" },
  { startTime: "9:30 AM", endTime: "10:00 AM", activity: "Name that Star Trek Quote hosted by Robb Pearlman", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Wednesday February 25 2026" },
  { startTime: "9:30 AM", endTime: "11:00 AM", activity: "Autograph Session: Doug Jones, Avaah Blackwell, Raven Dauda, David Benjamin Tomlinson, Todd Stashwick", location: "Sapphire Dining Room, 5", day: "Wednesday February 25 2026" },
  { startTime: "9:30 AM", endTime: "8:30 PM", activity: "Lightspeed Fine Art Gallery Open", location: "Aquanauts, 12 Aft (Adventure Ocean-Port Side)", day: "Wednesday February 25 2026" },
  { startTime: "10:00 AM", endTime: "10:45 AM", activity: "LifeTrek: From Naptown to Red Carpets Book Excerpt Reading by Anthony Montgomery", location: "Imperial Lounge, 5", day: "Wednesday February 25 2026" },
  { startTime: "10:00 AM", endTime: "11:00 AM", activity: "Star Trek: The Cruise Charity Auction hosted by Robert Picardo (Open Seating)", location: "The Lyric Theatre, 3", day: "Wednesday February 25 2026" },
  { startTime: "10:00 AM", endTime: "1:30 PM", activity: "Search For Spock Cryptic Clue Hunt", location: "Ship Wide", day: "Wednesday February 25 2026" },
  { startTime: "10:00 AM", endTime: "1:45 PM", activity: "Star Trek: The Cruise Group Community Room Open", location: "The Observation Lounge, 14 (Blue Moon)", day: "Wednesday February 25 2026" },
  { startTime: "10:00 AM", endTime: "2:00 PM", activity: "Fan Makeup with Thomas Surprenant (fee applies)", location: "Quark's Bar, 4 (Boleros)", day: "Wednesday February 25 2026" },
  { startTime: "11:00 AM", endTime: "Noon", activity: "Star Trek: Lower Decks Panel featuring Tawny Newsome, Eugene Cordero, Noël Wells hosted by Dr. Erin Macdonald (Open Seating)", location: "The Lyric Theatre, 3 & 4", day: "Wednesday February 25 2026" },
  { startTime: "11:00 AM", endTime: "Noon", activity: "Star Trek: Lower Decks Panel Simulcast", location: "Star Trek: The Cruise Promenade, 5", day: "Wednesday February 25 2026" },
  { startTime: "11:00 AM", endTime: "Noon", activity: "Ask Mama Nana with Nana Visitor", location: "Studio B, 3", day: "Wednesday February 25 2026" },
  { startTime: "11:00 AM", endTime: "12:30 PM", activity: "Autograph Session: Walter Koenig, Max Grodénchik, Tanya Lemani, Sean Kenney, Sandra Gimpel", location: "Sapphire Dining Room, 4", day: "Wednesday February 25 2026" },
  { startTime: "11:30 AM", endTime: "12:30 PM", activity: "Science Seminar: Why Are There So Many Humanoids in Star Trek? presented by Dr. Mohamed Noor", location: "Imperial Lounge, 5", day: "Wednesday February 25 2026" },
  { startTime: "Noon", endTime: "12:30 PM", activity: "Cruise Collective Pre-Ceremony Meet-Up", location: "Sports Court, 13", day: "Wednesday February 25 2026" },
  { startTime: "12:15 PM", endTime: "1:45 PM", activity: "Photo Session: Robert Picardo", location: "Sapphire Dining Room, 5", day: "Wednesday February 25 2026" },
  { startTime: "12:15 PM", endTime: "1:45 PM", activity: "Autograph Session: Chase Masterson, Jonathan Frakes, Marina Sirtis", location: "Sapphire Dining Room, 5", day: "Wednesday February 25 2026" },
  { startTime: "12:30 PM", endTime: "1:00 PM", activity: "Cruise Collective Assimilation Ceremony", location: "Pool Stage, 11", day: "Wednesday February 25 2026" },
  { startTime: "1:00 PM", endTime: "", activity: "Door and Window Decorating Judging Completed", location: "Ship Wide", day: "Wednesday February 25 2026" },
  { startTime: "1:00 PM", endTime: "2:15 PM", activity: "Cruise Collective Assimilation Party featuring Band 47", location: "Pool Stage, 11", day: "Wednesday February 25 2026" },
  { startTime: "1:15 PM", endTime: "2:15 PM", activity: "The Music of Star Trek featuring David Ludwig (The Julliard School) and Nick DiBerardino (The Curtis Institute of Music), with musicians from The Curtis Institute of Music", location: "Studio B, 3", day: "Wednesday February 25 2026" },
  { startTime: "1:15 PM", endTime: "2:15 PM", activity: "Star Trek Instant Meme Game hosted by Dr. Trek: Larry Nemecek", location: "Imperial Lounge, 5", day: "Wednesday February 25 2026" },
  { startTime: "2:00 PM", endTime: "3:00 PM", activity: "Star Trek: Enterprise Panel featuring John Billingsley, Connor Trinneer, Anthony Montgomery, and Dominic Keating hosted by Lolita Fatjo (Open Seating)", location: "The Lyric Theatre, 3 & 4", day: "Wednesday February 25 2026" },
  { startTime: "2:00 PM", endTime: "3:00 PM", activity: "Star Trek: Enterprise Panel Simulcast", location: "Star Trek: The Cruise Promenade, 5", day: "Wednesday February 25 2026" },
  { startTime: "2:15 PM", endTime: "3:00 PM", activity: "Fantasy Flash Fiction hosted by Robb Pearlman", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Wednesday February 25 2026" },
  { startTime: "2:30 PM", endTime: "3:30 PM", activity: "Our Sixty Years with Star Trek (On Both Sides of the Road) presented by Michael and Denise Okuda", location: "Studio B, 3", day: "Wednesday February 25 2026" },
  { startTime: "2:30 PM", endTime: "3:30 PM", activity: "Cupcake Decorating with Zoë Steiner (Ticket required. Sold out)", location: "Replicator Sushi, 5 (Izumi)", day: "Wednesday February 25 2026" },
  { startTime: "3:00 PM", endTime: "3:30 PM", activity: "Friends of Bill W.", location: "Prime Directive Grille, 4 (Chops)", day: "Wednesday February 25 2026" },
  { startTime: "3:00 PM", endTime: "4:00 PM", activity: "Science and Whisky: A Toast to Montgomery Scott hosted by Dr. Erin Macdonald (Ticket required. Sold out)", location: "Sapphire Dining Room, 3", day: "Wednesday February 25 2026" },
  { startTime: "3:00 PM", endTime: "5:00 PM", activity: "Beta Shift Karaoke Lounge", location: "The Observation Lounge, 14 (Blue Moon)", day: "Wednesday February 25 2026" },
  { startTime: "3:15 PM", endTime: "4:15 PM", activity: "Art and Sole: Sketch your Shoes presented by Noël Wells", location: "Imperial Lounge, 5", day: "Wednesday February 25 2026" },
  { startTime: "3:30 PM", endTime: "5:00 PM", activity: "Live Music", location: "Scotty's Taproom, 5 (Duck and Dog Pub)", day: "Wednesday February 25 2026" },
  { startTime: "3:45 PM", endTime: "4:45 PM", activity: "Blackjack Tournament: Final Table with Marina Sirtis (fee applies)", location: "Casino Royale, 4", day: "Wednesday February 25 2026" },
  { startTime: "3:45 PM", endTime: "5:15 PM", activity: "Roddenberry Entertainment Presents: Trek Nation Documentary Viewing", location: "Studio B, 3", day: "Wednesday February 25 2026" },
  { startTime: "4:00 PM", endTime: "5:30 PM", activity: "Autograph Session: Connor Trinneer, Dominic Keating, and Anthony Montgomery", location: "Sapphire Dining Room, 5", day: "Wednesday February 25 2026" },
  { startTime: "5:00 PM", endTime: "5:30 PM", activity: "Icebreaker Meetup hosted by The Morale Officers", location: "Scotty's Taproom, 5 (Duck and Dog Pub)", day: "Wednesday February 25 2026" },
  { startTime: "5:00 PM", endTime: "6:00 PM", activity: "Star Trek Fleet Command Panel featuring Gina Yashere and Zoë Steiner hosted by Rebekah Partridge", location: "Imperial Lounge, 5", day: "Wednesday February 25 2026" },
  { startTime: "5:00 PM", endTime: "9:00 PM", activity: "Fan Makeup with Thomas Surprenant (fee applies)", location: "Quark's Bar, 4 (Boleros)", day: "Wednesday February 25 2026" },
  { startTime: "5:15 PM", endTime: "5:45 PM", activity: "Trek Nation Documentary Panel featuring Rod Roddenberry and Trevor Roth", location: "Studio B, 3", day: "Wednesday February 25 2026" },
  { startTime: "5:30 PM", endTime: "6:00 PM", activity: "Guess Who Star Trek edition hosted by Robb Pearlman", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Wednesday February 25 2026" },
  { startTime: "5:30 PM", endTime: "6:30 PM", activity: "LGBTQIA Meetup hosted by The Morale Officers", location: "The Observation Lounge, 14 (Blue Moon)", day: "Wednesday February 25 2026" },
  { startTime: "6:00 PM", endTime: "7:15 PM", activity: "Autograph Session: Anthony Rapp, Gina Yashere, Zoë Steiner (Guests with Red SeaPass Cards)", location: "Sapphire Dining Room, 5", day: "Wednesday February 25 2026" },
  { startTime: "6:30 PM", endTime: "7:45 PM", activity: "A Visit to Original Star Trek: The Man Trap Script Reading directed by Nana Visitor (Guests with Blue SeaPass Cards)", location: "The Lyric Theatre, 3 & 4", day: "Wednesday February 25 2026" },
  { startTime: "7:00 PM", endTime: "7:30 PM", activity: "Sing-A-Long with Band 47", location: "Quark's Bar, 4 (Boleros)", day: "Wednesday February 25 2026" },
  { startTime: "7:00 PM", endTime: "10:00 PM", activity: "Beta Shift Karaoke Lounge", location: "The Observation Lounge, 14 (Blue Moon)", day: "Wednesday February 25 2026" },
  { startTime: "8:00 PM", endTime: "8:30 PM", activity: "Guess Who Star Trek edition hosted by Robb Pearlman", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Wednesday February 25 2026" },
  { startTime: "8:00 PM", endTime: "9:30 PM", activity: "Q's Costume Contest Prejudging", location: "Scotty's Taproom, 5 (Duck and Dog Pub)", day: "Wednesday February 25 2026" },
  { startTime: "8:30 PM", endTime: "9:45 PM", activity: "Autograph Session: Anthony Rapp, Gina Yashere, Zoë Steiner (Guests with Blue SeaPass Cards)", location: "Sapphire Dining Room, 5", day: "Wednesday February 25 2026" },
  { startTime: "9:00 PM", endTime: "9:30 PM", activity: "Sing-A-Long with Band 47", location: "Quark's Bar, 4 (Boleros)", day: "Wednesday February 25 2026" },
  { startTime: "9:00 PM", endTime: "10:15 PM", activity: "A Visit to Original Star Trek: The Man Trap Script Reading directed by Nana Visitor (Guests with Red SeaPass Cards)", location: "The Lyric Theatre, 3 & 4", day: "Wednesday February 25 2026" },
  { startTime: "10:00 PM", endTime: "11:30 PM", activity: "Q's Costume Party featuring DJ Miss Ninja", location: "Star Trek: The Cruise Promenade, 5", day: "Wednesday February 25 2026" },
  { startTime: "10:45 PM", endTime: "11:15 PM", activity: "Q's Costume Contest hosted by John de Lancie", location: "Star Trek: The Cruise Promenade, 5", day: "Wednesday February 25 2026" },
  { startTime: "10:45 PM", endTime: "11:15 PM", activity: "Q's Costume Contest Simulcast (Open Seating)", location: "The Lyric Theatre, 3 & 4", day: "Wednesday February 25 2026" },
  { startTime: "11:00 PM", endTime: "1:00 AM", activity: "Star Trek Movie Under The Stars: Star Trek V: The Final Frontier", location: "Pool Deck, 11", day: "Wednesday February 25 2026" },
  { startTime: "11:15 PM", endTime: "Midnight", activity: "10th Anniversary Showing: Star Trek: Beyond (Open Seating)", location: "The Lyric Theatre, 3 & 4", day: "Wednesday February 25 2026" },
  { startTime: "11:30 PM", endTime: "2:00 AM", activity: "Q's Costume Party Continuum featuring DJ Miss Ninja", location: "Imperial Lounge, 5", day: "Wednesday February 25 2026" },
  { startTime: "7:00 AM", endTime: "", activity: "Star Trek: The Cruise Docks In Coco Cay", location: "", day: "Thursday February 26 2026" },
  { startTime: "9:00 AM", endTime: "10:15 AM", activity: "Star Trek: Picard Episode on the Promenade Screen: The Last Generation", location: "Star Trek: The Cruise Promenade, 5", day: "Thursday February 26 2026" },
  { startTime: "9:00 AM", endTime: "6:00 PM", activity: "ECP Guest Services Desk Open", location: "Deck 5, Aft", day: "Thursday February 26 2026" },
  { startTime: "10:00 AM", endTime: "10:45 AM", activity: "Royal Caribbean presents: Visual Trivia: City Skylines", location: "Imperial Lounge, 5", day: "Thursday February 26 2026" },
  { startTime: "10:00 AM", endTime: "4:00 PM", activity: "Star Trek: The Cruise Group Community Room Open", location: "The Observation Lounge, 14 (Blue Moon)", day: "Thursday February 26 2026" },
  { startTime: "Noon", endTime: "12:45 PM", activity: "Royal Caribbean presents: Name That Tune: Y2K", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Thursday February 26 2026" },
  { startTime: "1:00 PM", endTime: "2:45 PM", activity: "Star Trek Movie Matinee: Star Trek III: The Search for Spock", location: "Pool Deck, 11", day: "Thursday February 26 2026" },
  { startTime: "1:00 PM", endTime: "3:00 PM", activity: "Open Play Pickleball", location: "Sports Court, 13", day: "Thursday February 26 2026" },
  { startTime: "3:00 PM", endTime: "3:30 PM", activity: "Friends of Bill W.", location: "Prime Directive Grille, 4 (Chops)", day: "Thursday February 26 2026" },
  { startTime: "3:00 PM", endTime: "6:00 PM", activity: "ECP Next Cruise Lounge Open", location: "ECP Next Cruise Lounge, 6", day: "Thursday February 26 2026" },
  { startTime: "3:30 PM", endTime: "5:00 PM", activity: "Live Music", location: "Scotty's Taproom, 5 (Duck and Dog Pub)", day: "Thursday February 26 2026" },
  { startTime: "4:00 PM", endTime: "4:30 PM", activity: "Behind the Bar with Quark featuring bartender Armin Shimerman", location: "Quark's Bar, 4 (Boleros)", day: "Thursday February 26 2026" },
  { startTime: "4:30 PM", endTime: "", activity: "All Aboard", location: "", day: "Thursday February 26 2026" },
  { startTime: "4:30 PM", endTime: "5:30 PM", activity: "Star Trek: Starfleet Academy Panel featuring Robert Picardo, Tawny Newsome, Gina Yashere, Zoë Steiner, and Avaah Blackwell hosted by Robb Pearlman (Open Seating)", location: "The Lyric Theatre, 3 & 4", day: "Thursday February 26 2026" },
  { startTime: "4:30 PM", endTime: "5:30 PM", activity: "Star Trek: Starfleet Academy Panel Simulcast", location: "Star Trek: The Cruise Promenade, 5", day: "Thursday February 26 2026" },
  { startTime: "4:30 PM", endTime: "5:30 PM", activity: "In the Hot Seat with Connor Trinneer and Special Guest Anthony Rapp", location: "Studio B, 3", day: "Thursday February 26 2026" },
  { startTime: "4:30 PM", endTime: "10:00 PM", activity: "Leap Event Tech Photo/Auto Sales Office Open", location: "Studio B Lobby, 3 Aft", day: "Thursday February 26 2026" },
  { startTime: "5:00 PM", endTime: "5:30 PM", activity: "Icebreaker Meetup hosted by The Morale Officers", location: "Scotty's Taproom, 5 (Duck and Dog Pub)", day: "Thursday February 26 2026" },
  { startTime: "5:30 PM", endTime: "6:00 PM", activity: "Bar Trivia hosted by The Morale Officers", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Thursday February 26 2026" },
  { startTime: "5:30 PM", endTime: "6:30 PM", activity: "LGBTQIA Meetup hosted by Robb Pearlman", location: "The Observation Lounge, 14 (Blue Moon)", day: "Thursday February 26 2026" },
  { startTime: "6:00 PM", endTime: "7:15 PM", activity: "Autograph Session: John de Lancie, Denise Crosby, Nana Visitor, Robert Picardo (Guests with Red SeaPass Cards)", location: "Sapphire Dining Room, 5", day: "Thursday February 26 2026" },
  { startTime: "6:30 PM", endTime: "7:45 PM", activity: "Star Trek: The Cruise Variety Show featuring Special Guests (Guests with Blue SeaPass Cards)", location: "The Lyric Theatre, 3 & 4", day: "Thursday February 26 2026" },
  { startTime: "7:00 PM", endTime: "9:00 PM", activity: "Beta Shift Karaoke Lounge", location: "The Observation Lounge, 14 (Blue Moon)", day: "Thursday February 26 2026" },
  { startTime: "7:15 PM", endTime: "8:15 PM", activity: "Love Letters featuring Jonathan Frakes and Marina Sirtis", location: "Studio B, 3", day: "Thursday February 26 2026" },
  { startTime: "7:30 PM", endTime: "8:15 PM", activity: "Star Trek Trivia: Malcolm's Red Hot Reed-Alert Rounders with Special Guest Dominic Keating", location: "Imperial Lounge, 5", day: "Thursday February 26 2026" },
  { startTime: "8:00 PM", endTime: "8:30 PM", activity: "Bar Trivia hosted by The Morale Officers", location: "The Enterprise Bar, 4 (Schooner Bar)", day: "Thursday February 26 2026" },
  { startTime: "8:30 PM", endTime: "9:45 PM", activity: "Autograph Session: John de Lancie, Denise Crosby, Nana Visitor, Robert Picardo (Guests with Blue SeaPass Cards)", location: "Sapphire Dining Room, 5", day: "Thursday February 26 2026" },
  { startTime: "9:00 PM", endTime: "9:45 PM", activity: "Star Trek Trivia: Tarima's Terrific First-Daughter Trivia Teasers with Special Guest Zoë Steiner", location: "Imperial Lounge, 5", day: "Thursday February 26 2026" },
  { startTime: "9:00 PM", endTime: "10:15 PM", activity: "Star Trek: The Cruise Variety Show featuring Special Guests (Guests with Red SeaPass Cards)", location: "The Lyric Theatre, 3 & 4", day: "Thursday February 26 2026" },
  { startTime: "9:15 PM", endTime: "10:15 PM", activity: "Love Letters featuring Jonathan Frakes and Marina Sirtis", location: "Studio B, 3", day: "Thursday February 26 2026" },
  { startTime: "10:00 PM", endTime: "Midnight", activity: "Trip, Travis, and Malcom's Voyage Home Karaoke Party", location: "Imperial Lounge, 5", day: "Thursday February 26 2026" },
  { startTime: "10:30 PM", endTime: "1:00 AM", activity: "The Voyage Home After Party with DJ Miss Ninja", location: "The Observation Lounge, 14 (Blue Moon)", day: "Thursday February 26 2026" },
  { startTime: "10:45 PM", endTime: "11:45 PM", activity: "Starfleet Academy Episode 8 Premiere at Sea (Open Seating)", location: "The Lyric Theatre, 3 & 4", day: "Thursday February 26 2026" },
  { startTime: "11:00 PM", endTime: "1:00 AM", activity: "Star Trek Movie Under The Stars: Star Trek IV: The Voyage Home", location: "Pool Deck, 11", day: "Thursday February 26 2026" },
];

export default scheduleData;
